name: first ci try
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  jobs1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "give it a try"
      - run: echo "on the actions"
      - run: echo "in eos2git"
